export default englishStrings = {
  WELCOME_BACK: 'Welcome Back',
  WELCOME: 'Welcome',
  SIGN_IN: 'Sign in',
  SIGN_UP: 'Sign up',
  SIGN_IN_ALL_CAPS: 'SIGN IN',
  SIGN_UP_ALL_CAPS: 'SIGN UP',
  LOG_IN_TO: 'Log in to your existing account of BookStore',
  OR: 'OR',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  FORGET_PASSWORD: 'Forget password?',
  DONT_HAVE: "Don't have an account?",
  CREATE_AN: 'Create an account to continue : )',
  FULL_NAME: 'Full name',
  CONFiRM_PASSWORD: 'Confirm password',
  ALREADY_HAVE: 'Already have an account?',
  DISCOVER: 'Discover',
  SHOW_MORE: 'Show more...',
  NO_FAV: 'No Favorites',
  MY_FAV: 'My Favorites',
  NO_ITEM_IN_CART: 'No Items in cart',
  MY_CART: 'My Cart',
  NO_NOTIFICATION: 'No_Notifications',
  HELLO: 'hello',
  VIEW_YOUR_PROFILE: 'View your profile',
  REQUIRED: '*Required',
  SHORT_PASSWORD: '*Short Password',
  PASSWORD_MUST_MATCH: '*Passwords must match',
  NAME_IS_TO_SMALL: '*Name is too small',
  AUTHORS: 'Authors',
  NO_ITEMS_IN_CART: 'No items in cart',
  ITEMS: 'items',
  ITEM: 'item',
  SUB_TOTAL: 'Sub Total',
  CHECK_OUT: 'Check out',
  NO_NOTIFICATION: 'No Notifications',
  MY_NOTIFICATION: 'My Notifications',
  AUTHOR_DETAILS: 'Author Details',
  BOOKS_SOLD: 'books sold',
  BOOK_DETAILS: 'Book Details',
  BUY_NOW: 'Buy Now',
  ADD_TO_CART: 'Add to cart',
  REMOVE_FROM_CART: 'Remove from cart',
  CHANGE_PASSWORD: 'Change Password',
  OLD_PASSWORD: 'old password',
  NEW_PASSWORD: 'new password',
  CONFIRM_NEW_PASSWORD: 'confirm new password',
  SUBMIT: 'Submit',
  NAME: 'Name',
  MESSAGE: 'Message',
  SEND: 'Send',
  TOO_SHORT: '*Too Short',
  INVALID_INPUT: '*Invalid input',
  ENTER_YOUR_PASSWORD: 'Enter your password',
  VERIFY: 'Verify',
  ADD_NEW_ADDRESS: 'Add new address',
  LANGUAGE: 'Languages',
  CONTACT_US: 'Contact us',
  ABOUT_US: 'About us',
  SETTINGS: 'Settings',
  SIGN_OUT: 'Sign Out',
  YOUR_PROFILE: 'Your profile',
  CHANGE_LANGUAGE: 'Change language',
  VERIFY_ITS_YOU: 'Verify its you',
  EDIT_YOUR_PROFILE: 'Edit Your Profile',
  BOOK_NAME: 'Book name',
  SEARCH: 'Search',
  RESULT: 'Result',
  RESULTS: 'Results',
  SEARCH_FOR_RESULTS: 'Search for results',
  ANIMATIONS: 'Animations',
  PHONE_NUMBER: 'Phone No',
  EDIT: 'Edit',
  SAVE: 'Save',
  SENT: 'Sent!',
  CHECK_YOUR_IN_BOX: 'Recovery mail has been send check your inbox',
  GET_RECOVERY_EMAIL: 'Get recovery email',
  FORGET_PASSWORD_WITHOUT_QUESTION: 'Forget password',
  OK: 'Ok',
};
